In [1]:
import numpy as np

In [14]:
m = np.random.randint (0, 20, (4, 6))
print(m)

[[13  8  1  6 19  3]
 [ 3 12 15 14  0 18]
 [11  1  3  5 13 12]
 [ 4 14  2 17 10 10]]


In [15]:
# Количество строк, не содержащих ни одного нулевого элемента

stk, stol = m[np.where(m.min(axis=1) != 0)].shape
print(stk)

3


In [16]:
# Максимальное из чисел, встречающихся в заданной матрице более одного раза

elm, count = np.unique(m, return_counts=True)
print(max(elm[count > 1]))

14
