In [1]:
import numpy as np

m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [2]:
print(m[1, 0])

5


In [3]:
m[1, :]

matrix([[5, 6, 7, 8]])

In [4]:
m[:, 2]

matrix([[3],
        [7],
        [5]])

In [5]:
m[1, 2:]

matrix([[7, 8]])

In [6]:
m[0:2, 1:3]

matrix([[2, 3],
        [6, 7]])

In [7]:
cols = [0, 1, 3]
m[:, cols]

matrix([[1, 2, 4],
        [5, 6, 8],
        [9, 1, 7]])

In [8]:
m.shape

(3, 4)

In [9]:
m.max()

9

In [10]:
m.max(axis=1)

matrix([[4],
        [8],
        [9]])

In [11]:
m.max(axis=0)

matrix([[9, 6, 7, 8]])

In [12]:
m.mean()

4.833333333333333

In [13]:
m.sum()

58

In [14]:
print(np.logical_and(m>=3, m<=7))

[[False False  True  True]
 [ True  True  True False]
 [False False  True  True]]
